runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  # Add any environment variables you need here, such as API keys or settings.
  # EXAMPLE_VAR: "example_value"

handlers:
  - url: /static
    static_dir: static/
    
  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10

instance_class: F2
