runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  # Add any environment variables you need here, such as API keys or settings.
  # EXAMPLE_VAR: "example_value"
  # API_KEY: "your_api_key_here"

handlers:
  - url: /static
    static_dir: static/
    
  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.5
  min_instances: 1
  max_instances: 2

resources:
  cpu: 0.25
  memory_gb: 0.25
  disk_size_gb: 10

instance_class: F1

# To saty in the Google Cloud Free Tier when using the App Engine, make sure:
  # Environment:
    # Deploy to the Standard Environment, instead of the Flexible Environment.
    # Avaliable runtime: python37, python39, nodejs16, java11, and more.
  # Usage limits: 
    # 28 hours per day of F1 instances
    # 9 hours per day of B1 instances
    # 1 GB of outbound data transfer per day